#!/usr/bin/env bash
# This script displays information about subdomains.

print_subdomain_details ()
{
	res=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1)
	record=$(echo "$res" | awk '{print $4}')
	ip_addr=$(echo "$res" | awk '{print $5}')
	echo "The subdomain $2 is a $record record and points to $ip_addr"

}

if [ "$#" -eq 2 ]; then
	print_subdomain_details "$1" "$2";
else
	print_subdomain_details "$1" "www";
	print_subdomain_details "$1" "lb-01";
	print_subdomain_details "$1" "web-01";
	print_subdomain_details "$1" "web-02";
fi
