#!/usr/bin/env bash
# This script Installs and configures HAproxy on a brand new server and
# configures it to redistribute traffic between two servers web-01 and web-02

# update package repository
sudo apt update -y

# install haproxy 
sudo apt install haproxy -y

# configure load balancing 
fe_text="\nfrontend web-fe\n\tmode http\n\tbind *:80\n\tdefault_backend web-be\n"
be_text="backend web-be\n\tbalance roundrobin\n\tmode http\n\tserver 279151-web-01 100.26.49.192:80 check\n\tserver 279151-web-02 107.22.143.52:80 check\n"

sudo sed -i "\$a\\$fe_text" /etc/haproxy/haproxy.cfg
sudo sed -i "\$a\\$be_text" /etc/haproxy/haproxy.cfg
sudo sed -i '$a\ENABLED=1' /etc/default/haproxy

# enable haproxy to start at boot
sudo systemctl enable haproxy

# start haproxy
sudo service haproxy start

# reload
sudo service haproxy reload
