#!/usr/bin/env bash
# This script does the following:
#    Creates the file /var/run/myscript.pid containing its PID
#    Displays To infinity and beyond indefinitely
#    Displays I hate the kill command when receiving a SIGTERM signal
#    Displays Y U no love me?! when receiving a SIGINT signal
#    Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ >> /var/run/myscript.pid

deleteandterminate() {
	rm /var/run/myscript.pid
	exit
}

handlesigterm() {
	echo "I hate the kill command"
	deleteandterminate
}

handlesigint() {
	echo "Y U no love me?!"
}

trap handlesigterm SIGTERM
trap handlesigint SIGINT
trap deleteandterminate SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
