#!/usr/bin/env bash
# This script prints 'To infinity and beyond indefinitely' and catches SIGTERM signals

_handler() {
	echo "I am invincible!!!"
}

trap _handler SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
