#!/usr/bin/env bash
# This script displays numbers from 1 to 100 in the following order:
#	FizzBuzz if the number is a multiple of 3 and 5
#	Fizz if the number is a multiple of 3
#	Buzz if the number is a multiple of 5
#	the number if it does not meet the above criteria

i=1
while ((i <= 100)); do
	if ((i % 3 == 0 && i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
