#!/usr/bin/env bash
# This script displays the contents of `/etc/passwd` file in the format username:user_id:directory_path

while IFS=":" read -r line; do
	echo "$line" | cut -d ":" -f 1,3,6
done < /etc/passwd
