#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes using a while loop:
#	- displays hours from 0 to 12
#	- displays minutes from 1 to 59

h=0
while ((h < 13)); do
	echo "Hour: $h"
	m=1
	while ((m < 60)); do
		echo "$m"
		((m++))
	done
	((h++))
done
